export const PROXIMITY_CHAT_RADIUS = 22;
export const NEARBY_INDICATOR_RADIUS = 22;

export const SATELLITE_MIN_INTERVAL_MS = 240_000;
export const SATELLITE_MAX_INTERVAL_MS = 420_000;
export const SATELLITE_DURATION_MS = 12_000;
